# docker-compose.yml
version: '3.8'

services:
  metroflow-api:
    build: 
      context: .  # Build the image from the Dockerfile in the current directory
      args:
        - NODE_ENV=production
    container_name: metroflow-api
    restart: unless-stopped # Automatically restart if it stops, unless manually stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - CACHE_TTL_SECONDS=120
      - GTFS_STATIC_URL_NYCT=${GTFS_STATIC_URL_NYCT} # Reads from .env file on the HOST running docker-compose
      - GTFS_STATIC_URL_LIRR=${GTFS_STATIC_URL_LIRR}
      - GTFS_STATIC_URL_MNR=${GTFS_STATIC_URL_MNR}
      - STATIC_REFRESH_SCHEDULE=${STATIC_REFRESH_SCHEDULE}
      - STATIC_REFRESH_TIMEZONE=${STATIC_REFRESH_TIMEZONE}
      - TZ=America/New_York
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      # Mount host directories/named volumes into the container
      - metroflow-data:/app/data # Mount named volume 'metroflow-data' to /app/data in container
      - metroflow-logs:/app/logs # Mount named volume 'metroflow-logs' to /app/logs
      - metroflow-temp:/app/temp-downloads # Mount named volume for temp downloads
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

# Define the named volumes
volumes:
  metroflow-data:
    driver: local
  metroflow-logs:
    driver: local
  metroflow-temp:
    driver: local
